/*---------------------------------------------------------------------------------------------------------
3) MAGNITUDE ANALYSIS 
	-- PURPOSE: group data by category for comparaison pusposes. comparing categories allows us to define the best ot highest contributor and the lowest and worst contributor to the whole data
------------------------------------------------------------------------------------------------------------*/
   
   -- TASK1 : Find the total number of customers by countries
SELECT 
country,
COUNT(customer_id )As total_number_of_customer
FROM gold_dim_customers
GROUP BY country
ORDER BY total_number_of_customer DESC;

-- TASK2 : Find total customer by gender 
SELECT
gender,
COUNT(customer_id) AS total_number_by_gender
FROM gold_dim_customers
GROUP BY gender
ORDER BY total_number_by_gender DESC;

-- TASK3 : Find total product by category 
SELECT
category,
COUNT(product_key) AS total_product
FROM gold_dim_products
GROUP BY category
ORDER BY total_product DESC;

-- TASK4 :Calculate the average cost in each category 
SELECT
category,
AVG (cost) AS AVG_cost
FROM gold_dim_products
GROUP BY category
ORDER BY AVG_cost DESC;

-- TASK5: Calculate total revenue by category
SELECT 
p.category,
SUM(s.sales_amount) AS total_revenue
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC;

-- TASK6: Calculate total revenue generated by each customer 
SELECT
s.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) As total_revenue
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY 
s.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- TASK7 : Calculate total items or quantity sold by country
SELECT
c.country,
SUM(s.quantity) AS total_item
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_customers As c
ON s.customer_key = s.customer_key
GROUP BY country
ORDER BY total_item DESC;